name: Integration tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install `yarn`
        run: npm install -g yarn
      
      - name: Install dependencies
        run: yarn

      - name: Run integration tests
        run: yarn test:int
        env:
          SHARESIGHT_USERNAME: ${{ secrets.SHARESIGHT_USERNAME }}
          SHARESIGHT_PASSWORD: ${{ secrets.SHARESIGHT_PASSWORD }}
